import { chromium } from 'playwright-core';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});
page.on('pageerror',err=>{throw err});
await page.goto('http://127.0.0.1:4340');
await page.evaluate(()=>localStorage.clear());await page.reload();
await page.locator('textarea').fill('One way SFO to Tokyo on October 8, 2026. Only nonstop.');
await page.getByRole('button',{name:'Analyze Trips'}).click();
await page.getByText('Recommended route',{exact:false}).waitFor({timeout:180000});
await page.screenshot({path:'.logs/one-way-mobile.png',fullPage:true});
let r=await page.evaluate(()=>JSON.parse(localStorage.getItem('flightfinder:last')));
if(r.intent.tripType!=='one_way'||r.demo||!r.journeys?.length||r.journeys[0].flights.length!==1)throw Error('One-way assertion failed');
console.log('LIVE one way:',r.journeys[0].total,r.journeys[0].flights[0].source);
await page.getByRole('button',{name:'New search'}).click();
await page.locator('textarea').fill('Multi-city: SFO to Tokyo October 8 2026, stay 5 nights in Tokyo, then Seoul for 3 nights, then return to SFO. Only nonstop flights.');
await page.getByRole('button',{name:'Analyze Trips'}).click();
await page.getByText('Recommended route',{exact:false}).waitFor({timeout:180000});
r=await page.evaluate(()=>JSON.parse(localStorage.getItem('flightfinder:last')));
await writeFile('.logs/live-journey.json',JSON.stringify(r));
if(r.demo||r.journeys[0].flights.length!==3||r.journeys[0].total!==r.journeys[0].flights.reduce((s,f)=>s+f.price,0))throw Error('Total assertion failed');
console.log('LIVE multi-city:',r.journeys[0].total,r.journeys[0].stays);
await page.screenshot({path:'.logs/multi-city-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.getByPlaceholder(/Change anything/).fill('Stay 4 nights in Seoul instead, keep Tokyo 5 nights and the same departure date.');
await page.getByRole('button',{name:'Send',exact:true}).click();
await page.getByText('Recommended route',{exact:false}).waitFor({timeout:180000});
r=await page.evaluate(()=>JSON.parse(localStorage.getItem('flightfinder:last')));
if(r.journeys[0].stays[1].nights!==4)throw Error('Follow-up nights not applied');
console.log('LIVE follow-up:',r.journeys[0].total,r.journeys[0].stays.map(s=>s.nights));
await browser.close();
